title: Project Bookworm
logo: /assests/img/logo.png
theme: jekyll-theme-minimal
description: A large-scale library management solution for loaning large quantities of books to a smaller group of borrowers.
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
