<<<<<<< HEAD
#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 14, 2018 02:25:46 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import entrysmall_support

def vp_start_gui(text):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    entrysmall_support.set_Tk_var(text)
    top = Entry_Form (root)
    entrysmall_support.init(root, top)
    root.mainloop()

w = None
def create_Entry_Form(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    entrysmall_support.set_Tk_var()
    top = Entry_Form (w)
    entrysmall_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Entry_Form():
    global w
    w.destroy()
    w = None


class Entry_Form:
    def __init__(self, top=None, entry="Enter:"):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("200x159+700+347")
        top.title("Entry Form")
        top.configure(background="#474747")
        top.configure(highlightbackground="#f0f0f0f0f0f0")



        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.08, rely=0.31,height=30, relwidth=0.82)
        self.Entry1.configure(background="#828282")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=164)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.25, rely=0.06, height=31, width=99)
        self.Label1.configure(activebackground="#474747")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(activeforeground="#474747")
        self.Label1.configure(background="#474747")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#ffffff")
        #self.Label1.configure(text='''Enter ISBN:''')
        self.Label1.configure(textvariable = str(entry))

        self.Button1 = Button(top)
        self.Button1.place(relx=0.28, rely=0.63, height=44, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#828282")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Submit''')
        self.Button1.configure(width=87)






if __name__ == '__main__':
    vp_start_gui()



=======
#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 14, 2018 02:25:46 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import entrysmall_support

def vp_start_gui(text):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    entrysmall_support.set_Tk_var(text)
    top = Entry_Form (root)
    entrysmall_support.init(root, top)
    root.mainloop()

w = None
def create_Entry_Form(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    entrysmall_support.set_Tk_var()
    top = Entry_Form (w)
    entrysmall_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Entry_Form():
    global w
    w.destroy()
    w = None


class Entry_Form:
    def __init__(self, top=None, entry="Enter:"):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("200x159+700+347")
        top.title("Entry Form")
        top.configure(background="#474747")
        top.configure(highlightbackground="#f0f0f0f0f0f0")



        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.08, rely=0.31,height=30, relwidth=0.82)
        self.Entry1.configure(background="#828282")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=164)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.25, rely=0.06, height=31, width=99)
        self.Label1.configure(activebackground="#474747")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(activeforeground="#474747")
        self.Label1.configure(background="#474747")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#ffffff")
        #self.Label1.configure(text='''Enter ISBN:''')
        self.Label1.configure(textvariable = str(entry))

        self.Button1 = Button(top)
        self.Button1.place(relx=0.28, rely=0.63, height=44, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#828282")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Submit''')
        self.Button1.configure(width=87)






if __name__ == '__main__':
    vp_start_gui()



>>>>>>> ade12e8163ce3463b78236abe5051e4cc8d5d57b
